### ISSUE TITLE
Expose OpenID Profile Picture if available

### ISSUE THREAD

**Issue by joshsadler** [moov-io/identity#44]
We want to support showing the photo of a person signed in and their teammates using Moov. Since users may be signing in with an OpenID Connect provider, we may get the picture URL from the profile claim.

Consider adding a proxy path, like 

`/api/identities/:id/picture`

or

`/api/profile-photo/:full-path-to-third-party-picture`

Either way, the service acting as a proxy for the photo will eliminate some CSP issues on the frontend.

A 404 is an acceptable failure status.

**Comment by adamdecaf** [comment]
@joshsadler Do you want an Identicon or some blank profile image served if we can't discover it from the OIDC provider? Maybe long term? 

Not every provider will offer it and some users may not have one set.

**Comment by joshsadler** [comment]
@adamdecaf no, I'd be most useful to know definitively whether a profile has a photo or not so I can fallback to initials in the web UI. That's why a 404 OR a flag on the user model would be great.

**Comment by jmbrown412** [comment]
@joshsadler I've added the following:
A GET call to /authentication/register will return the imageUrl if one is returned from authn.
A POST call to /authentication/authenticated will also return the imageUrl if one was provided from authn.

Let me know if this works for ya. Thanks!

**Comment by joshsadler** [comment]
@jmbrown412 POST /authentication/authenticated is great for the current user, though this one is missing:
- GET /session (returns the current users profile info, used to check if user is already signed in on the frontend)

Is there a way to retrieve the image by user identityID? If not, it will be needed on these endpoints as well so that we can show the image of users other than the one that is signed in.

- GET /identities
- GET /identities/:identityID

**Comment by jmbrown412** [comment]
@joshsadler 
GET /session , GET /identities and GET /identities/identityID will return the ImageUrl

**Comment by adamdecaf** [comment]
https://github.com/moov-io/identity/pull/45 did this work right? Can we close out this issue?

**Comment by joshsadler** [comment]
@jmbrown412 #45 appears to have covered the majority of this issue, however, I'm observing the following behavior on production where we're using Google auth:

`imageUrl` is "https://lh3.googleusercontent.com/a-" for my user, so surely something is cutting off part of the URL. Might it have something to do with the hyphen?

**Comment by jmbrown412** [comment]
https://github.com/moov-io/authn/blob/master/pkg/providers/openid/controller_generic_oidc.go#L166

It looks to me this should be passing through the value from the provider. It does look like there is possibly something odd with that hyphen though. I'm not sure how to troubleshoot this.

@joshsadler Have you tried with any other auth provider and what was the result?

**Comment by joshsadler** [comment]
@jmbrown412 no, we don't have another auth provider set up. I'd try a test case with the Google profile image URL structure. Mine should be "https://lh3.googleusercontent.com/a-/AOh14Gjxg6PqK7j7pBd7JPck6w7Bl-J4kJXKFoL3hDlm=s100"

**Comment by jmbrown412** [comment]
@InfernoJJ I've dug into this and `url.Parse` can handle "https://lh3.googleusercontent.com/a-/AOh14Gjxg6PqK7j7pBd7JPck6w7Bl-J4kJXKFoL3hDlm=s100".  Not sure how to test this with https://github.com/coreos/go-oidc and actually perform auth with google. Is it possible the issue could be with this lib? It seems like this is a pretty solid and widely used lib for this.

**Comment by jmbrown412** [comment]
Verified it works in prod. Closing issue.
