### ISSUE TITLE
Move out common libraries to `moov-io/base`

### ISSUE THREAD

**Issue by InfernoJJ** [moov-io/identity#60]
We should move out common libraries like `pkg/logging`, `pkg/database`, `pkg/config`, and `pkg/stime` into our `moov-io/base` project so every service isn't directly tied to identity for this common functionality.

**Comment by InfernoJJ** [comment]
This will require updating the `eng-project-templater` project as well to use the new library location.

**Comment by InfernoJJ** [comment]
Some of these libraries are small enough we could just use code generation that's provided as part of `eng-project-templater` to build it out.

**Comment by vxio** [comment]
Does `moov-io/identity` generally have the most up-to-date libraries?

**Comment by InfernoJJ** [comment]
Yeah renovate comes around with PRs to update it. The problem is a bunch of
common libraries are in identity but used everywhere else.

**Comment by vxio** [comment]
Sounds good, I'll start working on this.
